vich_uploader:
    db_driver: orm

    mappings:
        sneakers:
            uri_prefix: /uploads/sneakers
            upload_destination: '%kernel.project_dir%/public/uploads/sneakers'
            namer: vich_uploader.namer_origname

        profiles:
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: vich_uploader.namer_origname

