vich_uploader:
    db_driver: orm

    mappings:
        sneakers:
            uri_prefix: /uploads/sneakers
            upload_destination: '%kernel.project_dir%/public/uploads/sneakers'
            namer: vich_uploader.namer_origname
            
            delete_on_update: true
            delete_on_remove: true
        profiles:
            uri_prefix: /uploads/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/profiles'
            namer: vich_uploader.namer_origname

            delete_on_update: true
            delete_on_remove: true

