vich_uploader:
    db_driver: orm

    mappings:
        sneakers:
            uri_prefix: /images/sneakers
            upload_destination: '%kernel.project_dir%/public/images/sneakers'
        profiles:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
